### ISSUE TITLE
Draft and send a prep email to participants

### ISSUE THREAD

**Issue by jcoyne** [PenguinParadigm/samvera18apis#3]
Christina will look for the earlier draft.

Add: Have admin permissions.

**Comment by cmharlow** [comment]
Good morning!
 
We are excited to meet with you all Tuesday, October 9th, at 9 AM for our Samvera Connect 2018 Workshop: Library Data APIs, Design to Deploy. We wanted to send you some preparation materials for the bootcamp. We hope you’re able to go through some installation work before that Tuesday.
 
- Materials: Our Bootcamp info is in this GitHub repository: https://github.com/PenguinParadigm/samvera18apis. Materials, schedule, tech set up info, and slides are actively being added & updated there.
- Communication: Feel free to open issues on that Github repository or join our #taco-workshop Samvera Slack channel. Or you can email us directly.
- Technical setup is all detailed here https://github.com/PenguinParadigm/samvera18apis#technical-prep. They include:
    - laptop with modern web browser and internet connection.
    - our workshop GitHub repository on your computer (with mechanism to update / pull down latest changes on Monday morning).
    - installed the latest, stable version (18.03.1-ce) of Docker Community Edition;
    - installed latest, stable version (1.11) of Go & set up your Go workspace.
    - set up a free AWS account & awscli connected to that free account.
    - pulled down & can run [this localstack docker image](https://hub.docker.com/r/localstack/localstack/) for use in your Go workspace.
- Technical setup MVP [minimum viable product]: Try to at least have Go and Localstack ready to go Monday morning. We have scheduled a lunch break for us where we can also help you set up / install Docker and AWS if needed.
 
If you’re curious about the back-story to this workshop, you can read our wiki or code at the Stanford Digital Library TACO repository: https://github.com/sul-dlss-labs/taco or our TACO Truck repository documentation: https://github.com/sul-dlss/taco-truck. We’ll basically be walking through building a mini version of TACO (‘TAQUITO’).
 
Thanks all!
Christina

**Comment by cmharlow** [comment]
Above okay?

**Comment by mjgiarlo** [comment]
@cmh2166 LGTM

**Comment by jcoyne** [comment]
@cmh2166 bump go version from 1.10.2 to 1.11. Other than that, looks good!

**Comment by cmharlow** [comment]
Thanks @mjgiarlo - but looking for other workshop facilitators to vet.

Thanks @jcoyne - i'm going to send this out today if there are no issues (@aaron-collier?)

**Comment by cmharlow** [comment]
done. cannot close this until i get permissions however.

**Comment by mjgiarlo** [comment]
:ok: unwatching.
